### ISSUE TITLE
Dockerfile and VARIANT argument are no longer required

### ISSUE THREAD

**Issue by johnbullnz** [pamelafox/python-project-template#4]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> N/A

### Any log messages given by the failure
> N/A

### Expected/desired behavior
> N/A

### OS and Version?
> Windows 10.

### Versions
>

### Mention any other details that might be useful

Thanks for setting up this repo.

The Docker container image is now set in `.devcontainer/devcontainer.json` (as mcr.microsoft.com/vscode/devcontainers/python:3.11-bullseye). The following changes are needed to the repository to align:
- Delete `devcontainer/Dockerfile` (now uses the mcr.microsoft.com image)
- Update `README.md` to remove references to `VARIANT`.

**Comment by pamelafox** [comment]
Thanks for the fix, merged!
